name: electricity-consumption-forecast
channels:
  - conda-forge
dependencies:
  - python==3.10.4
  - pip==22.2.2
  - pip:
    - papermill==2.3.3
    - jupyter==1.0.0
    - nb_black==1.0.7
    - numpy==1.22.0
    - pandas==1.3.5
    - meteostat==1.5.11
    - altair==4.2.0
    - matplotlib==3.5.2
    - holidays==0.14.2
    - scikit-lego==0.6.11
    - scikit-learn==1.1.1
